In [3]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

#Data contoh (ganti dengan data anda)
data = np.array([[2.0, 5.0],
                 [1.0, 4.0],
                 [3.0, 6.0]])

#Inisialisasi objek MinMaxScaler
scaler = MinMaxScaler()

# fit dan transformasi data menggunakan Min-Max Scoling
scaled_data = scaler.fit_transform(data)

print("Data Asli:")
print(data)

print("/nData setelah Min-Max Scaling:")
print(scaled_data)

Data Asli:
[[2. 5.]
 [1. 4.]
 [3. 6.]]
/nData setelah Min-Max Scaling:
[[0.5 0.5]
 [0.  0. ]
 [1.  1. ]]


In [4]:
import numpy as np
from sklearn.preprocessing import StandardScaler

# Data contoh (ganti dengan data anda)
data = np.array([[2.0, 5.0],
                 [1.0, 4.0],
                 [3.0, 6.0]])

#Inisialisasi objek StandardScaler
scaler = StandardScaler()

#fit dan transformasi data menggunakan Z-Score Transformation
z_score_data = scaler.fit_transform(data)

print("Data Asli:")
print(data)

print("/nData setelah Z-Score Transformation:")
print(z_score_data)

Data Asli:
[[2. 5.]
 [1. 4.]
 [3. 6.]]
/nData setelah Z-Score Transformation:
[[ 0.          0.        ]
 [-1.22474487 -1.22474487]
 [ 1.22474487  1.22474487]]


In [5]:
import numpy as np

#Data contoh(ganti dengan data anda)
data = np.array([200, 300, 400, 500, 600])

#menentukan faktor penggerseran (scaling factor)
#misalnya 1000 untuk mengubah ke rentang 0-1
scaling_factor = 1000

#melakukan transformasi Decimal Scaling
scaled_data = data / scaling_factor

print("Data Asli:")
print(data)

print("/Data setelah Decimal Scaling")
print(scaled_data)

Data Asli:
[200 300 400 500 600]
/Data setelah Decimal Scaling
[0.2 0.3 0.4 0.5 0.6]
